# Generates a Markdown reference for the framework's NixOS option
# declarations. Run via `nix build .#options-doc`; the docs pipeline
# (apps.docs in rust-packages.nix) copies the result into
# docs/mdbook/src/options.md.
#
# Standard tooling: `pkgs.nixosOptionsDoc` is the same renderer
# nixpkgs uses for the official NixOS option reference. It consumes
# the `options` attribute of an `lib.evalModules` result.
#
# The scope modules reference `inputs.self.packages.<system>.nixfleet-*`,
# which we'd otherwise have to actually build. For documentation we
# only need the *option declarations*, never the resolved config — so
# we pass stubs in specialArgs and set `_module.check = false` to skip
# strict module-arg validation.
{...}: {
  perSystem = {
    pkgs,
    lib,
    ...
  }: let
    stubInputs = {
      self.packages.${pkgs.system} = {
        nixfleet-agent = pkgs.hello;
        nixfleet-control-plane = pkgs.hello;
        nixfleet-cli = pkgs.hello;
      };
    };

    docFor = file: let
      eval = lib.evalModules {
        modules = [
          file
          ({...}: {_module.check = false;})
        ];
        specialArgs = {
          inherit pkgs;
          inputs = stubInputs;
        };
      };
    in
      pkgs.nixosOptionsDoc {inherit (eval) options;};

    # Each entry: heading shown above the section + module file.
    # Modules with non-NixOS shapes (helpers, fragments) are not listed.
    sections = [
      {
        heading = "Trust roots — `nixfleet.trust.*`";
        file = ./_trust.nix;
      }
      {
        heading = "Agent — `services.nixfleet-agent.*`";
        file = ./scopes/nixfleet/_agent.nix;
      }
      {
        heading = "Control plane — `services.nixfleet-control-plane.*`";
        file = ./scopes/nixfleet/_control-plane.nix;
      }
      {
        heading = "Operator workstation tooling — `nixfleet.operator.*`";
        file = ./scopes/nixfleet/_operator.nix;
      }
      {
        heading = "Binary cache (consumer) — `services.nixfleet-cache.*`";
        file = ./scopes/nixfleet/_cache.nix;
      }
    ];

    sectionMd = {
      heading,
      file,
    }:
      pkgs.runCommand "section.md" {} ''
        printf '## %s\n\n' ${lib.escapeShellArg heading} > $out
        cat ${(docFor file).optionsCommonMark} >> $out
        printf '\n' >> $out
      '';
  in {
    packages.options-doc = pkgs.runCommand "options-doc.md" {} ''
      cat > $out <<'EOF'
      # Module options reference

      Auto-generated by `pkgs.nixosOptionsDoc` from the option
      declarations under `modules/`. Regenerated on every
      `nix run .#docs` build. Edit the `description` strings in the
      module sources to change anything below.

      EOF
      ${lib.concatMapStringsSep "\n" (s: "cat ${sectionMd s} >> $out") sections}
    '';
  };
}
