# tests/harness/nodes/cp.nix
#
# Control-plane microVM node for the harness.
#
# Stub behavior: serves a static fleet.resolved.json over HTTPS on :8443
# using mTLS (fleet CA + CP server cert generated by mkTlsCerts). Uses a
# tiny darkhttpd process so we don't depend on crates/control-plane yet.
#
# Note: the v0.2 control-plane skeleton has landed in
# `crates/nixfleet-control-plane`, but the harness still serves a static
# fixture over socat because no `services.nixfleet-control-plane` NixOS
# module exists yet. Migrating to a real CP-backed unit is a follow-up
# project (not a comment cleanup); when the service module lands the
# mTLS wiring (env and cert paths) stays the same.
{
  lib,
  pkgs,
  testCerts,
  resolvedJsonPath,
  ...
}: {
  # Expose certs + fixture at stable paths on the host VM. Agent microVMs
  # reach this via the qemu user-net gateway (10.0.2.2:8443 from agent
  # POV → host VM's :8443).
  environment.etc = {
    "nixfleet-harness/ca.pem".source = "${testCerts}/ca.pem";
    "nixfleet-harness/cp-cert.pem".source = "${testCerts}/cp-cert.pem";
    "nixfleet-harness/cp-key.pem".source = "${testCerts}/cp-key.pem";
    "nixfleet-harness/fleet.resolved.json".source = resolvedJsonPath;
  };

  networking.firewall.allowedTCPPorts = [8443];

  # Static-fixture scaffold: serves the resolved artifact over TLS. The
  # reconciler-side verify path is exercised by the verify-artifact CLI
  # and the signed-roundtrip scenario, so the CP here only needs to hand
  # out bytes. Replacing this with a real `services.nixfleet-control-plane`
  # is a future harness-migration project (see header note).
  systemd.services.harness-cp = let
    # `socat` gives us TLS termination + static file response without
    # pulling in a full webserver. It's in nixpkgs and starts in <100ms.
    responder = pkgs.writeShellScript "harness-cp-responder" ''
      set -eu
      body=$(cat /etc/nixfleet-harness/fleet.resolved.json)
      len=$(printf '%s' "$body" | wc -c)
      printf 'HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: %d\r\nConnection: close\r\n\r\n%s' "$len" "$body"
    '';
    socatOpts = lib.concatStringsSep "," [
      "OPENSSL-LISTEN:8443"
      "reuseaddr"
      "fork"
      "cert=/etc/nixfleet-harness/cp-cert.pem"
      "key=/etc/nixfleet-harness/cp-key.pem"
      "cafile=/etc/nixfleet-harness/ca.pem"
      "verify=1"
    ];
    launcher = pkgs.writeShellScript "harness-cp-launcher" ''
      exec ${pkgs.socat}/bin/socat -v "${socatOpts}" "EXEC:${responder}"
    '';
  in {
    description = "Nixfleet harness CP stub (serves fleet.resolved.json)";
    wantedBy = ["multi-user.target"];
    after = ["network.target"];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${launcher}";
      Restart = "on-failure";
      RestartSec = 2;
    };
  };

  system.stateVersion = lib.mkDefault "24.11";
}
