# tests/harness/nodes/cp.nix
#
# Smoke / fleet-N stub CP. Serves a static fleet.resolved.json over
# HTTPS on :8443 using mTLS (fleet CA + CP server cert generated by
# mkTlsCerts). Uses socat for TLS termination; no SQLite, no in-memory
# state, no /v1/agent/* routes — just bytes-on-the-wire.
#
# Why this stub stays after `services.nixfleet-control-plane` landed:
# this node pairs with `agent.nix`, whose only job is to prove the
# harness's mTLS plumbing (cert mounts + qemu user-net gateway +
# microvm /etc share) with a curl client. The real CP serves
# `/v1/agent/*`, not `GET /` returning a static JSON; switching the
# smoke + fleet-N (2/5/10) variants to the real-binary path
# (cp-real.nix + agent-real.nix) is redundant — boot-recovery /
# teardown / secret-hygiene already exercise the real wire under
# the same harness substrate. The fleet-N variants are scaling tests
# for the substrate itself; doubling their per-VM cost (real binary
# vs. one-shot curl) without testing anything new is the wrong tradeoff.
#
# When the smoke path needs to assert real CP semantics it should
# fork to a new scenario built on cp-real.nix, not migrate this one.
{
  lib,
  pkgs,
  testCerts,
  resolvedJsonPath,
  ...
}: {
  # Expose certs + fixture at stable paths on the host VM. Agent microVMs
  # reach this via the qemu user-net gateway (10.0.2.2:8443 from agent
  # POV → host VM's :8443).
  environment.etc = {
    "nixfleet-harness/ca.pem".source = "${testCerts}/ca.pem";
    "nixfleet-harness/cp-cert.pem".source = "${testCerts}/cp-cert.pem";
    "nixfleet-harness/cp-key.pem".source = "${testCerts}/cp-key.pem";
    "nixfleet-harness/fleet.resolved.json".source = resolvedJsonPath;
  };

  networking.firewall.allowedTCPPorts = [8443];

  # Static-fixture scaffold: serves the resolved artifact over TLS. The
  # reconciler-side verify path is exercised by the verify-artifact CLI
  # and the signed-roundtrip scenario, so the CP here only needs to hand
  # out bytes. The real `services.nixfleet-control-plane` module
  # explicitly does NOT serve a `GET /` route; see header for why this
  # stub stays.
  systemd.services.harness-cp = let
    # `socat` gives us TLS termination + static file response without
    # pulling in a full webserver. It's in nixpkgs and starts in <100ms.
    responder = pkgs.writeShellScript "harness-cp-responder" ''
      set -eu
      body=$(cat /etc/nixfleet-harness/fleet.resolved.json)
      len=$(printf '%s' "$body" | wc -c)
      printf 'HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: %d\r\nConnection: close\r\n\r\n%s' "$len" "$body"
    '';
    socatOpts = lib.concatStringsSep "," [
      "OPENSSL-LISTEN:8443"
      "reuseaddr"
      "fork"
      "cert=/etc/nixfleet-harness/cp-cert.pem"
      "key=/etc/nixfleet-harness/cp-key.pem"
      "cafile=/etc/nixfleet-harness/ca.pem"
      "verify=1"
    ];
    launcher = pkgs.writeShellScript "harness-cp-launcher" ''
      exec ${pkgs.socat}/bin/socat -v "${socatOpts}" "EXEC:${responder}"
    '';
  in {
    description = "Nixfleet harness CP stub (serves fleet.resolved.json)";
    wantedBy = ["multi-user.target"];
    after = ["network.target"];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${launcher}";
      Restart = "on-failure";
      RestartSec = 2;
    };
  };

  system.stateVersion = lib.mkDefault "24.11";
}
