[book]
title = "NixFleet Documentation"
authors = ["abstracts33d"]
language = "en"
src = "."

[build]
build-dir = "../../result-docs"

[output.html]
git-repository-url = "https://github.com/abstracts33d/nixfleet"
